---
title: "Introduction to Data Science, BIOS 611"
author: "Matthew Biggs"
output: html_document
---

### Course information

The goals of this class will be to:

1. Achieve profficiency in R (specifically the ["Tidyverse"](`r4ds`))
2. Gain familiarity with a suite of data science tools
3. Master the practices of good data science

Topics will include gaining proficiency with R, data wrangling, data quality control and cleaning, data visualization, exploratory data analysis, introductory applied optimization, with an overall emphasis on the principles of good data science-particularly reproducible research. 

The course will also develop familiarity with software tools for data science best practices, such as Git, Docker, Jupyter, Make and Nextflow.

The course will emphasize "learning by doing", with the bulk of the grade coming from several creative data science projects.

### Practices of Good Data Science

1. Analyses are reproducible and portable
2. Collaboration is easy
    + Data is accessible
    + Code is easy to read and interpret
    + Work is transparent
3. Code is trustworthy and robust
4. Clients can easily find and interpret analyses

```{r clean_table, include = FALSE}
manif_url = url('https://www.oreilly.com/ideas/a-manifesto-for-agile-data-science')
bash_url = 'http://cs.lmu.edu/~ray/notes/bash/'
rprdc_url = 'http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285'
```

### Course Schedule

Fall 2018, class will be held on Mondays and Wednesdays from 9:05--10:20 AM. Wednesday afternoons there will be an additional lab period from 3:35--4:35 PM. 

Before class, students will have read the assigned material from the textbook [R for Data Science](http://r4ds.had.co.nz/). The first 45 minutes of class (9:05--9:50) will be spent working through the exercises and getting hands-on practice with R. We will take a 2--5 minute break, then the remainder of the time will be spend discussing a tool (Mondays) or a topic (Wednesdays). 

Lab time will be spent working on assigned data science projects.

Class   | R4DS | Tools and Topics | Project  | Slides
--------|------|------------------|----------|-------------- 
Introduction to the course  | NA                                                                                    | Syllabus and Principles of Data Science | Start brainstorming P1  | 
Getting started with R      | [1.4.2--1.6 ](http://r4ds.had.co.nz/introduction.html)                                | [Rstudio](https://www.rstudio.com/)     |                         |
Data visualization          | [3](http://r4ds.had.co.nz/data-visualisation.html)                                    | Data Visualization                      | Choose a data set       | 
Programming and scripts     | [4](http://r4ds.had.co.nz/workflow-basics.html) and [6](http://r4ds.had.co.nz/workflow-scripts.html)  | Git and GitHub          |                         |
Dplyr                       | [5](http://r4ds.had.co.nz/transform.html#introduction-2)                              | [Iteration](`manif_url`)                | Start visualizing       |
Exploratory data analysis   | [7.1--7.4](http://r4ds.had.co.nz/exploratory-data-analysis.html#introduction-3)       | [Intro to bash](`bash_url`)             |                         |
Visualizing covariation     | [7.5--7.7](http://r4ds.had.co.nz/exploratory-data-analysis.html#covariation)          | [Reproducibility](`rprdc_url`)          | Put draft on github     |
Walkthrough 1               | NA                                                                                    |                                         |                         |
Project 1 presentations     | NA                                                                                    |                                         | Start brainstorming P2  |
Tibbles and data import     | [9--11.2](http://r4ds.had.co.nz/wrangle-intro.html)                                   | Rscript                                 |                         |
Parsing and writing files   | [11.3--11.6](http://r4ds.had.co.nz/data-import.html#parsing-a-vector)                 | Collaboration                           | Find a data set         |
Relational data: table Joins| [13.1--13.4](http://r4ds.had.co.nz/relational-data.html#introduction-7)               | Bash scripts and Make                   |                         |
Joins continued and set ops | [13.5--13.7](http://r4ds.had.co.nz/relational-data.html#filtering-joins)              | Data Science Spotlight                  | Wrangle that data       |
Strings and Regex           | [141](http://r4ds.had.co.nz/strings.html)                                             | SQL                                     |                         |
Factors                     | [15](http://r4ds.had.co.nz/factors.html)                                              | Literate Programming                    | Put draft on github     |
Walkthrough 2               | NA                                                                                    |                                         |                         |
Project 2 presentations     | NA                                                                                    |                                         | Start brainstorming P3  |
Dates and times             | [16](http://r4ds.had.co.nz/dates-and-times.html)                                      | Jupyter                                 |                         |
Programming and pipes       | [17--18](http://r4ds.had.co.nz/program-intro.html)                                    | Communication                           | Choose a data set       |
Functions                   | [19](http://r4ds.had.co.nz/functions.html#introduction-12)                            | Docker                                  |                         |
Vectors                     | [20](http://r4ds.had.co.nz/vectors.html)                                              | Unit Tests and CI                       | Plan functions          |
For loops                   | [21](http://r4ds.had.co.nz/iteration.html)                                            | Remote servers                          |                         |
Graphics for communication  | [28](http://r4ds.had.co.nz/graphics-for-communication.html)                           | Data Science Spotlight                  | Pipes and unit tests    |
Walkthrough 3               | NA                                                                                    |                                         |                         |
Project 3 presentations     | NA                                                                                    |                                         | Start brainstorming P4  |
Linear models               | [23.1--23.3](http://r4ds.had.co.nz/model-basics.html#introduction-15)                 | Modeling                                |                         |
Optimization and modeling   | NA                                                                                    | Big Data                                | Choose a data set       |
More modeling in R          | [23.4--23.6](http://r4ds.had.co.nz/model-basics.html#formulas-and-model-families)     | Nextflow                                |                         |
Modeling diamonds           | [24.1--24.2](http://r4ds.had.co.nz/model-building.html#introduction-16)               | Inkscape, GIMP                          | Build a model, organize |
Rmd                         | [29--30](http://r4ds.had.co.nz/r-markdown-formats.html)                               | Data Science Spotlight, Continuous Learning |                     |
Walkthrough 4               | NA                                                                                    |                                         | Submit draft on github  |
Final project presentations | NA                                                                                    |                                         |                         |
Final project presentations | NA                                                                                    |                                         |                         |

 


...

### Projects

There will be four projects during the semester during which students will be asked to identify a data set, analyze it in R, apply new tools discussed in class, and effectively communicate the results. Prior to each project, the students will walk through a prepared example that demonstrates the tools they will be expected to use.

Walk-throughs will be graded on exactness of outputs (numbers and figures must be as expected).
Projects will be graded using a [matrix]() based on the principles of data science emphasized in class.  


#### Project 1

* Use existing data set in R
* Create github repository
* Read data into R
* Produce a figure
* Communicate results

#### Project 2

* Find or generate data set
* Create github repository
* Wrangle the data using Dplyr
* Perform at least one table join 
* Produce two figures
* Communicate results

#### Project 3

* Find or generate data set
* Create github repository
* Organize code into functions
* Use the pipe in your code (R and Bash)
* Write at least one unit test for a function
* Produce a figure, and output a file
* Run your code on a remote server
* Communicate results

#### Project 4 (Final)

* Find or generate a meaningful data set
* Create github repository
* Use a Makefile or Nextflow script to organize project
* Use a model to desribe patterns in your data
* Communicate results in a blog post formatted in R markdown
...