## Homework 9
# Exercise 6 Docker (Followed by python Exercises 1 to 5).

1. Do the following under a folder called `Homework9`. Put All your 
   python scripts from previous Exercises: `hw9_1.py` to `hw9_5.py`.
   (This `Homework9/` folder will be your working directory.)
   Also make the following folders: `Homework9/output/`, `Homework9/py36`.

2. Write a Dockerfile under `Homework9/py36` that builds 
   a Docker image which only includes python3.6 and the following python packages:
   `numpy` and `pandas`.  
   Hint) Google how to install a python package. e.g. `pip`  
   Hint) The name of the public image is `python:3.6`.

3. Write a bash command that builds the Docker image (from part 2.) with a name 
   of "py36".
   (Keep in mind that we will eventually write a Makefile to automate all these
   procedures, so please save the bash commands for later.)
   (Recall that your working directory `Homework9/`)

4. Write bash commands that run on a Docker container "py36" `hw9_1.py`, 
   `hw9_2.py`, and `hw9_3.py` in a detached mode and 
   that save the printed outcomes as 
   `/output/hw9_1.txt`, `/output/hw9_2.txt`, and `/output/hw9_3.txt`, 
   respectively.
   The arguments to be passed to each file are:
   2 3 7 4 6  for `hw9_1.py`,
   5 2 17 for `hw9_2.py`, and
   nothing for `hw9_3.py`.

   (Hint: To get the output files, 
   instead of running `python ... > output.txt` in a `docker run` command,
   run a bash script `/bin/bash/ -c "python .... > output.txt"`.
   Otherwise, your append (`>`) operator will not be wrapped within `docker run` command
   but will act on all the previous things, i.e. on `docker run ... python ....`. ).

5. Write a bash command that pulls a publicly available Docker image
   `frolvlad/alpine-python-machinelearning`.

6. Write bash commands that run on a Docker container 
   ("frolvlad/alpine-python-machinelearning") 
   `hw9_4.py` and `hw9_5.py` and that save the printed outcomes as 
   `/output/hw9_4.txt` and `/output/hw9_5.txt`, respectively
   in a detached mode.
   The arguments to be passed to each file are:
   0 1 2  for `hw9_4.py` and
   3 5 for `hw9_5.py`.
   Hint:  use `/bin/sh/` instead of `/bin/bash/' for this container.


7. Write a bash command that prints out the list of file names in the output folder.

8. Finally, write a Makefile that
  (This step is not needed) 1. constructs the folder structure (from part 1), (This step is not needed)  
  2. builds and pulls a Docker image (from parts 2, 3 and 5),
  3. runs the three python scripts on a Docker container (part 4),  
  4. runs the other two python scripts on another Docker container (part 6), and  
  5. runs the bash command printing out the list of output files. (part 7).
  (Hint: Makefile will fail, if you have `$(pwd)` inside. In that case, you can
  replace them with `$(shell pwd)`.


Tips and notes)
1. Your final answer has only to include the followings:
  Homework9/Makefile
  Homework9/py36/Dockerfile
  Homework9/***.py
  Homework9/output/***.txt

2. Make sure that
   1) your Makefile and Dockerfile are executable without any error.
   2) your text files include correct results.
