build-image: Dockerfile.hw7
	docker build -t mf2g -f Dockerfile.hw7 . && touch $@

build-docker-image: build-image
	cp build-image build-docker-image
	
hw7_out.png: build-docker-image
	docker run -it --rm -v $(shell pwd):/unc -w /unc mf2g /bin/bash -c \
	"make -f Makefile.hw7 hw7_out.png -Bnd | make2graph | dot -Tpng -o hw7_out.png"
