
../data/outfig.png: ../data/elements-by-episode_538.csv
	Rscript rscript_with_make.R ../data/elements-by-episode_538.csv \
								../data/outfig.png
								
.PHONY: clean
clean:
	rm ../data/outfig.png